import { ArrowUpRight, BriefcaseBusiness, CalendarDays, Check, ExternalLink, MapPin, Menu, Scissors, Sparkles, X } from 'lucide-react';
import { useState } from 'react';
import { Link, Route, Routes } from 'react-router-dom';

const projects = {
  prestige: { slug: 'prestige', title: 'Prestige Barber Co', type: 'Booking-first website concept', place: 'San Antonio, USA', accent: 'copper', cover: 'https://sc04.alicdn.com/kf/Acf091d3dbc4e4e38819280cfed4b125am.png', coverAlt: 'Premium dark editorial barber concept cover with copper accents', route: '/projects/prestige', short: 'Luxury grooming, made easy to book.', summary: 'A premium, mobile-first concept that replaces a temporary website with a clear service overview, location details and a direct booking path.', challenge: 'The public site was marked “Website Under Construction”, leaving the first impression unfinished.', solution: 'A confident landing page with clear services, contact details and a single next step: book an appointment.', external: 'https://booksy.com/en-us/1610801_prestige-barber-co_barber-shop_134789_san-antonio', externalLabel: 'Open booking flow', services: ['Classic cut', 'Fresh fade', 'Beard trim', 'Kids cuts'] },
  'day-hair': { slug: 'day-hair', title: 'Day Hair Habit', type: 'Bali salon experience concept', place: 'Uluwatu & Ubud, Bali', accent: 'green', cover: 'https://sc04.alicdn.com/kf/A0da1aecb72d64d5791e18fab623ef6a9l.png', coverAlt: 'Warm sand and botanical green editorial salon concept cover', route: '/projects/day-hair', short: 'A good hair day, wherever you are.', summary: 'A warm salon experience that helps visitors choose a location, find a treatment and move to booking without getting lost in a link hub.', challenge: 'The Instagram path relies on Linktree and multiple booking destinations for different Bali locations.', solution: 'A calm visual flow: choose Uluwatu or Ubud, discover a treatment, then continue to the existing booking channel.', external: 'https://linktr.ee/dayhairhabit', externalLabel: 'Open booking links', services: ['Hair cut', 'Styling', 'Coloring', 'Keratin', 'Scalp treatment'] },
  pitstop: { slug: 'pitstop', title: 'Pitstop Barbershop', type: 'Motorsport booking concept', place: 'Riverside, Nairobi', accent: 'red', cover: 'https://sc04.alicdn.com/kf/A348ef0c13ed84ea48c88632c1c954ddcS.png', coverAlt: 'Graphite and racing red editorial motorsport barber concept cover', route: '/projects/pitstop', short: 'Sharp looks. Fast pit stops.', summary: 'A motorsport-inspired concept that keeps the pit-crew identity while making service selection and booking more direct on mobile.', challenge: 'The brand has a strong idea, but a long service flow can make the first booking decision feel heavy.', solution: 'A faster pit-lane path: choose the service, understand the experience and enter the booking flow.', external: 'https://pitstopbarbershop.co.ke/', externalLabel: 'Open current site', services: ['The Main Race', 'Bodywork', 'Wheel service', 'The Chicane'] },
};

function Header() { const [open, setOpen] = useState(false); const close = () => setOpen(false); return <header className="portfolio-header" data-component="site-header"><Link className="portfolio-logo" to="/" onClick={close}>A<span>.</span></Link><button className="portfolio-menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button><nav className={open ? 'portfolio-nav open' : 'portfolio-nav'}><Link to="/" onClick={close}>Work</Link><a href="/#about" onClick={close}>About</a><a href="/#contact" onClick={close}>Contact</a></nav></header>; }
function ConceptFrame({ accent, label = 'Concept frame — no photography' }) { return <div className={`concept-frame ${accent}`} role="img" aria-label={label}><span className="concept-label">{label}</span><div className="frame-orbit" /><div className="frame-word">ALEXEY<br /><i>design</i></div></div>; }
function ProjectCover({ project, className = '' }) { return <div className={`project-cover ${project.accent} ${className}`}><img src={project.cover} alt={project.coverAlt} /><span className="cover-overlay" /><span className="cover-index">{project.slug === 'prestige' ? '01' : project.slug === 'day-hair' ? '02' : '03'}</span><span className="cover-caption">Self-initiated concept</span></div>; }
function ProjectPreview({ project }) { return <section className={`project-preview ${project.accent}`} data-component="interactive-project-preview"><div className="preview-top"><span>Live concept preview</span><span>01 / 04</span></div><div className="preview-hero"><div><span className="preview-brand">{project.title}</span><h2>{project.short}</h2><a className="preview-cta" href={project.external} target="_blank" rel="noreferrer">Book now <ArrowUpRight size={15} /></a></div><div className="preview-symbol">{project.accent === 'green' ? 'DAY' : project.accent === 'red' ? 'PIT' : 'P'}</div></div><div className="preview-services"><div className="preview-label">Choose your service</div>{project.services.map((service, index) => <a href={project.external} target="_blank" rel="noreferrer" key={service}><span>0{index + 1}</span><strong>{service}</strong><ArrowUpRight size={15} /></a>)}</div><div className="preview-footer"><span><MapPin size={14} /> {project.place}</span><a href={project.external} target="_blank" rel="noreferrer">Continue to booking <ExternalLink size={14} /></a></div></section>; }
function Home() { return <><section className="portfolio-hero" data-component="hero-section"><div><p className="eyebrow"><Sparkles size={15} /> Independent web designer</p><h1>Websites that<br /><em>move people.</em></h1><p className="hero-copy">I design clear, characterful websites for barbershops, salons and local service businesses.</p><a className="button primary" href="#work">See selected work <ArrowUpRight size={18} /></a></div><ConceptFrame accent="copper" label="Self-initiated portfolio" /></section><section className="work-section" id="work" data-component="work-grid"><div className="section-label">Selected concepts <span>03 projects</span></div><div className="project-grid">{Object.values(projects).map((project) => <Link className={`project-card ${project.accent}`} to={project.route} key={project.slug}><ProjectCover project={project} /><div className="project-meta"><span>{project.type}</span><ArrowUpRight size={18} /></div><h2>{project.title}</h2><p>{project.place}</p></Link>)}</div></section><section className="about-section" id="about" data-component="about-section"><p className="eyebrow">How I work</p><h2>Clarity first.<br /><em>Character always.</em></h2><p>I turn a service business into a simple digital journey: understand the offer, feel the brand, take the next step.</p></section><section className="contact-section" id="contact" data-component="contact-section"><div><p className="eyebrow">Available for website projects</p><h2>Have a good<br /><em>project in mind?</em></h2></div><div><p>Tell me what you are building and what needs to work better. I’ll reply with a focused direction.</p><span className="contact-note">Contact details can be added here</span></div></section></>; }
function ProjectPage({ project }) { return <main className={`project-page ${project.accent}`} data-component="project-page"><Link className="back-link" to="/">← Back to selected work</Link><div className="project-heading"><p className="eyebrow">{project.type} · {project.place}</p><h1>{project.title}</h1><p>{project.summary}</p></div><ProjectCover project={project} className="detail-cover" /><ProjectPreview project={project} /><div className="project-details"><article><span>Challenge</span><h2>{project.challenge}</h2></article><article><span>Direction</span><h2>{project.solution}</h2></article></div><div className="project-actions"><a className="button primary" href={project.external} target="_blank" rel="noreferrer">{project.externalLabel} <ExternalLink size={16} /></a><Link className="button secondary" to="/">View all projects</Link></div><p className="concept-disclaimer"><Check size={15} /> Self-initiated concept redesign — not official client work.</p></main>; }
function NotFound() { return <main className="not-found"><BriefcaseBusiness size={30} /><h1>Project not found</h1><Link to="/">Back to portfolio</Link></main>; }
export default function App() { return <div className="portfolio-shell"><Header /><Routes><Route path="/" element={<Home />} /><Route path="/projects/prestige" element={<ProjectPage project={projects.prestige} />} /><Route path="/projects/day-hair" element={<ProjectPage project={projects['day-hair']} />} /><Route path="/projects/pitstop" element={<ProjectPage project={projects.pitstop} />} /><Route path="*" element={<NotFound />} /></Routes><footer className="portfolio-footer" data-component="site-footer"><span>Alexey — web & product design</span><span>Concept projects · 2026</span><a href="#top">Back to top ↑</a></footer></div>; }
