// Bilingual content for the portfolio.
// EN is the international positioning (prices in EUR),
// RU keeps the local market (prices in RUB).

export const contacts = [
  { key: 'telegram', label: 'Telegram', value: '@morphlxng', href: 'https://t.me/morphlxng', icon: 'send' },
  { key: 'instagram', label: 'Instagram', value: '@morphlxng', href: 'https://instagram.com/morphlxng', icon: 'instagram' },
  { key: 'email', label: 'Email', value: 'nevizhin40@gmail.com', href: 'mailto:nevizhin40@gmail.com', icon: 'mail' },
];

export const content = {
  en: {
    meta: {
      title: 'Alexey — websites that book clients for barbershops & salons',
      description:
        'Independent web designer building clear, high-converting websites with online booking for barbershops, salons and local service businesses. Fixed pricing in EUR.',
    },
    nav: { work: 'Work', pricing: 'Pricing', about: 'About', start: 'Start', contact: 'Contact', cta: 'Get in touch' },
    hero: {
      eyebrow: 'Independent web designer',
      titleA: 'Websites that',
      titleB: 'sell for you.',
      copy: 'I design clear, characterful websites for barbershops, salons and local businesses. Booking in two taps — instead of “call us”.',
      ctaPricing: 'See pricing',
      ctaWork: 'View work',
    },
    pricing: {
      eyebrow: 'Services & pricing',
      titleA: 'Transparent.',
      titleB: 'No surprises on the invoice.',
      sub: 'Fixed price before we start. 50% upfront, the rest after approval.',
      badge: 'Most popular',
      cta: 'Talk on Telegram',
      note: 'Not your case? Write me — I’ll put together a custom offer for your goal.',
    },
    work: {
      eyebrow: 'Selected concepts',
      titleA: 'Work that',
      titleB: 'speaks for itself.',
      sub: 'Self-initiated concepts: how I see websites for service businesses. Real businesses, redesigned.',
    },
    about: {
      eyebrow: 'About me',
      titleA: 'Clarity first.',
      titleB: 'Character always.',
      lead: 'I’m Alexey — an independent web designer. I work with service businesses: barbershops, salons and studios that need a website working as hard as they do.',
      text: 'My work sits between clarity and character. The interface stays obvious and fast, while the brand gets enough personality to be remembered. No off-the-shelf templates. Remote, working with clients worldwide.',
    },
    contact: {
      eyebrow: 'Open for projects',
      titleA: 'Got an idea?',
      titleB: 'Write first.',
      sub: 'Tell me what you’re building and what should work better. I’ll reply with a concrete direction within a day.',
    },
    intake: {
      eyebrow: 'Start a project',
      titleA: 'Tell me about',
      titleB: 'your project.',
      sub: 'Fill this in and I’ll reply within a day. Prefer chat? Message me on Telegram.',
      name: 'Your name',
      business: 'Business / brand',
      contact: 'Email or Telegram',
      need: 'What do you need?',
      message: 'Details — goals, deadline, references',
      options: ['Landing page', 'Multi-page website', 'Design concept', 'Booking setup', 'Not sure yet'],
      submit: 'Send request',
      note: 'Opens your email app with a pre-filled message — or message me on Telegram.',
    },
    project: {
      back: '← Back to work',
      challenge: 'Challenge',
      solution: 'Solution',
      all: 'All work',
      note: 'Self-initiated concept — not an official client case.',
    },
    footer: { role: 'Alexey — web & product design', tagline: 'Concepts · 2026', top: 'Back to top ↑' },
    notFound: { title: 'Page not found', back: 'Back to portfolio' },
    pricingItems: [
      {
        name: 'Landing page',
        price: 'from €700',
        time: '5–7 days',
        featured: false,
        desc: 'A one-page site: services, prices, team and a booking button. Perfect for a barbershop or studio.',
        features: ['Design tailored to your brand', 'Mobile responsive', 'Form or booking button', 'Domain setup'],
      },
      {
        name: 'Multi-page website',
        price: 'from €1,400',
        time: '10–14 days',
        featured: true,
        desc: 'A full website with a service catalog, team pages, a work gallery and online booking.',
        features: ['Everything in Landing', 'Service & team pages', 'Online booking (Booksy / Fresha)', 'SEO basics & analytics', 'Training: how to edit content'],
      },
      {
        name: 'Design concept',
        price: 'from €400',
        time: '3–5 days',
        featured: false,
        desc: 'Homepage design without development — see your future site before we start building.',
        features: ['Homepage design mockup', 'Mobile version', '2 rounds of revisions', 'Figma files'],
      },
      {
        name: 'Booking setup',
        price: 'from €250',
        time: '1–2 days',
        featured: false,
        desc: 'Connecting online booking and basic setup to an existing website or profile.',
        features: ['Booking widget setup', 'Notification setup', 'Domain & email connection'],
      },
    ],
  },

  ru: {
    meta: {
      title: 'Alexey — сайты для барбершопов и салонов',
      description:
        'Независимый веб-дизайнер. Делаю понятные сайты с онлайн-записью для барбершопов, салонов и локального бизнеса. Фиксированная цена.',
    },
    nav: { work: 'Работы', pricing: 'Цены', about: 'Обо мне', start: 'Заявка', contact: 'Контакты', cta: 'Написать' },
    hero: {
      eyebrow: 'Независимый веб-дизайнер',
      titleA: 'Сайты, которые',
      titleB: 'продают за вас.',
      copy: 'Делаю понятные сайты с характером для барбершопов, салонов и локального бизнеса. Запись в два клика — вместо «позвоните нам».',
      ctaPricing: 'Смотреть цены',
      ctaWork: 'Работы',
    },
    pricing: {
      eyebrow: 'Услуги и цены',
      titleA: 'Прозрачно.',
      titleB: 'Без сюрпризов в счёте.',
      sub: 'Фиксированная цена до старта работ. Предоплата 50%, остальное — после приёмки.',
      badge: 'Популярный выбор',
      cta: 'Обсудить в Telegram',
      note: 'Не нашли свой случай? Напишите — соберу индивидуальное предложение под вашу задачу.',
    },
    work: {
      eyebrow: 'Избранные концепты',
      titleA: 'Работы, которые',
      titleB: 'говорят сами.',
      sub: 'Self-initiated концепты: как я вижу сайты для сервисного бизнеса.',
    },
    about: {
      eyebrow: 'Обо мне',
      titleA: 'Ясность прежде всего.',
      titleB: 'Характер — всегда.',
      lead: 'Я Алексей — независимый веб-дизайнер. Работаю с сервисным бизнесом: барбершопы, салоны, студии, которым нужен сайт, работающий так же усердно, как они сами.',
      text: 'Мои работы — между ясностью и характером. Интерфейс остаётся очевидным и быстрым, а бренд получает достаточно индивидуальности, чтобы запомниться. Никаких шаблонов «как у всех».',
    },
    contact: {
      eyebrow: 'Открыт для проектов',
      titleA: 'Есть идея?',
      titleB: 'Напишите первым.',
      sub: 'Расскажите, что строите и что должно работать лучше. Отвечу с конкретным направлением в течение дня.',
    },
    intake: {
      eyebrow: 'Начать проект',
      titleA: 'Расскажите о',
      titleB: 'вашем проекте.',
      sub: 'Заполните — отвечу в течение дня. Удобнее в переписке? Напишите в Telegram.',
      name: 'Ваше имя',
      business: 'Бизнес / бренд',
      contact: 'Email или Telegram',
      need: 'Что нужно?',
      message: 'Детали — цели, срок, примеры',
      options: ['Landing page', 'Многостраничный сайт', 'Дизайн-концепт', 'Запись и настройка', 'Пока не уверен'],
      submit: 'Отправить заявку',
      note: 'Откроется почтовое приложение с готовым письмом — или напишите в Telegram.',
    },
    project: {
      back: '← Назад к работам',
      challenge: 'Задача',
      solution: 'Решение',
      all: 'Все работы',
      note: 'Self-initiated концепт — не официальный кейс клиента.',
    },
    footer: { role: 'Alexey — web & product design', tagline: 'Концепты · 2026', top: 'Наверх ↑' },
    notFound: { title: 'Страница не найдена', back: 'Вернуться в портфолио' },
    pricingItems: [
      {
        name: 'Landing page',
        price: 'от 15 000 ₽',
        time: '5–7 дней',
        featured: false,
        desc: 'Одностраничный сайт: услуги, цены, мастера и кнопка записи. Идеально для барбершопа или студии.',
        features: ['Дизайн под ваш бренд', 'Адаптив под телефон', 'Форма или кнопка записи', 'Подключение домена'],
      },
      {
        name: 'Многостраничный сайт',
        price: 'от 30 000 ₽',
        time: '10–14 дней',
        featured: true,
        desc: 'Полноценный сайт с каталогом услуг, страницами мастеров, галереей работ и онлайн-записью.',
        features: ['Всё из Landing', 'Страницы услуг и мастеров', 'Онлайн-запись (YClients / Dikidi)', 'SEO-база и аналитика', 'Обучение: как менять контент'],
      },
      {
        name: 'Дизайн-концепт',
        price: 'от 8 000 ₽',
        time: '3–5 дней',
        featured: false,
        desc: 'Дизайн главной страницы без вёрстки — увидеть свой будущий сайт до старта разработки.',
        features: ['Дизайн-макет главной', 'Мобильная версия', '2 раунда правок', 'Файлы в Figma'],
      },
      {
        name: 'Запись и настройка',
        price: 'от 5 000 ₽',
        time: '1–2 дня',
        featured: false,
        desc: 'Подключение онлайн-записи и базовой настройки к уже работающему сайту или профилю.',
        features: ['Подключение виджета записи', 'Настройка уведомлений', 'Привязка домена и почты'],
      },
    ],
  },
};

// Concept projects (brand names stay in English in both languages).
export const projects = {
  prestige: {
    slug: 'prestige',
    title: 'Prestige Barber Co',
    type: 'Booking-first website concept',
    place: 'San Antonio, USA',
    accent: 'copper',
    cover: '/assets/images/prestige-cover.png',
    coverAlt: 'Premium dark editorial barber concept cover with copper accents',
    route: '/projects/prestige',
    short: 'Luxury grooming, made easy to book.',
    summary: 'A premium, mobile-first concept that replaces a temporary website with a clear service overview, location details and a direct booking path.',
    challenge: 'The public site was marked “Website Under Construction”, leaving the first impression unfinished.',
    solution: 'A confident landing page with clear services, contact details and a single next step: book an appointment.',
    external: 'https://booksy.com/en-us/1610801_prestige-barber-co_barber-shop_134789_san-antonio',
    externalLabel: 'Open booking flow',
    services: ['Classic cut', 'Fresh fade', 'Beard trim', 'Kids cuts'],
  },
  'day-hair': {
    slug: 'day-hair',
    title: 'Day Hair Habit',
    type: 'Bali salon experience concept',
    place: 'Uluwatu & Ubud, Bali',
    accent: 'green',
    cover: '/assets/images/day-hair-cover.png',
    coverAlt: 'Warm sand and botanical green editorial salon concept cover',
    route: '/projects/day-hair',
    short: 'A good hair day, wherever you are.',
    summary: 'A warm salon experience that helps visitors choose a location, find a treatment and move to booking without getting lost in a link hub.',
    challenge: 'The Instagram path relies on Linktree and multiple booking destinations for different Bali locations.',
    solution: 'A calm visual flow: choose Uluwatu or Ubud, discover a treatment, then continue to the existing booking channel.',
    external: 'https://linktr.ee/dayhairhabit',
    externalLabel: 'Open booking links',
    services: ['Hair cut', 'Styling', 'Coloring', 'Keratin', 'Scalp treatment'],
  },
  pitstop: {
    slug: 'pitstop',
    title: 'Pitstop Barbershop',
    type: 'Motorsport booking concept',
    place: 'Riverside, Nairobi',
    accent: 'red',
    cover: '/assets/images/pitstop-cover.png',
    coverAlt: 'Graphite and racing red editorial motorsport barber concept cover',
    route: '/projects/pitstop',
    short: 'Sharp looks. Fast pit stops.',
    summary: 'A motorsport-inspired concept that keeps the pit-crew identity while making service selection and booking more direct on mobile.',
    challenge: 'The brand has a strong idea, but a long service flow can make the first booking decision feel heavy.',
    solution: 'A faster pit-lane path: choose the service, understand the experience and enter the booking flow.',
    external: 'https://pitstopbarbershop.co.ke/',
    externalLabel: 'Open current site',
    services: ['The Main Race', 'Bodywork', 'Wheel service', 'The Chicane'],
  },
  arizona: {
    slug: 'arizona',
    title: 'Arizona',
    type: 'Tattoo studio concept',
    place: 'Kazan, Russia',
    accent: 'red',
    cover: '/assets/images/arizona-cover.svg',
    coverAlt: 'Arizona tattoo studio concept cover',
    href: '/concepts/arizona/',
    externalConcept: true,
  },
  pinky: {
    slug: 'pinky',
    title: 'Pinky',
    type: 'Nail studio concept',
    place: 'Voronezh, Russia',
    accent: 'copper',
    cover: '/assets/images/pinky-cover.svg',
    coverAlt: 'Pinky nail studio concept cover',
    href: '/concepts/pinky/',
    externalConcept: true,
  },
  detailing: {
    slug: 'detailing',
    title: 'Apex Detailing',
    type: 'Car detailing concept',
    place: 'Russia',
    accent: 'green',
    cover: '/assets/images/detailing-cover.svg',
    coverAlt: 'Apex detailing studio concept cover',
    href: '/concepts/detailing/',
    externalConcept: true,
  },
};
